import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { supabase } from "@/integrations/supabase/client";
import { Toaster } from "@/components/ui/sonner";
function NotFoundComponent() { return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold">404</h1><h2 className="mt-4 text-xl font-semibold">Página não encontrada</h2><p className="mt-2 text-sm text-muted-foreground">A página que você procura não existe ou foi movida.</p><div className="mt-6"><Link to="/" className="inline-flex rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Voltar ao início</Link></div></div></div>; }
function ErrorComponent({ error, reset }: { error: Error; reset: () => void }) { console.error(error); const router = useRouter(); useEffect(() => { reportLovableError(error, { boundary: "tanstack_root_error_component" }); }, [error]); return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-xl font-semibold">Não foi possível carregar a página</h1><p className="mt-2 text-sm text-muted-foreground">Algo deu errado. Tente novamente ou volte ao início.</p><div className="mt-6 flex justify-center gap-2"><button onClick={() => { router.invalidate(); reset(); }} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Tentar novamente</button><a href="/" className="rounded-md border px-4 py-2 text-sm font-medium">Início</a></div></div></div>; }
export const Route = createRootRouteWithContext<{ queryClient: QueryClient }>()({ head: () => ({ meta: [{ charSet: "utf-8" }, { name: "viewport", content: "width=device-width, initial-scale=1" }, { title: "NextSM — Service Desk" }, { name: "description", content: "Central de atendimento e gestão de chamados da NextSM." }], links: [{ rel: "stylesheet", href: appCss }] }), shellComponent: RootShell, component: RootComponent, notFoundComponent: NotFoundComponent, errorComponent: ErrorComponent });
function RootShell({ children }: { children: ReactNode }) { return <html lang="pt-BR"><head><HeadContent /></head><body>{children}<Scripts /></body></html>; }
function RootComponent() { const { queryClient } = Route.useRouteContext(); const router = useRouter(); useEffect(() => { const normalizeTitle = () => { const current = document.title || ""; const cleaned = current.replace(/Mundo\s*Vem(?:\s+Service\s+Desk)?/gi, "NextSM").replace(/\s*\|\s*$/g, "").trim(); if (cleaned !== current) document.title = cleaned || "NextSM — Service Desk"; }; normalizeTitle(); const observer = new MutationObserver(normalizeTitle); const title = document.querySelector("title"); if (title) observer.observe(title, { childList: true, characterData: true, subtree: true }); return () => observer.disconnect(); }, []); useEffect(() => { const { data: sub } = supabase.auth.onAuthStateChange((event) => { if (event !== "SIGNED_IN" && event !== "SIGNED_OUT" && event !== "USER_UPDATED") return; if (event === "SIGNED_OUT") { queryClient.cancelQueries(); queryClient.clear(); } router.invalidate(); if (event !== "SIGNED_OUT") queryClient.invalidateQueries(); }); return () => sub.subscription.unsubscribe(); }, [router, queryClient]); return <QueryClientProvider client={queryClient}><Outlet /><Toaster richColors position="top-right" /></QueryClientProvider>; }
