import { createFileRoute, Link, redirect, useNavigate } from "@tanstack/react-router";
import { supabase } from "@/integrations/supabase/client";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend, Cell } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export const Route = createFileRoute("/_authenticated/dashboard")({
  head: () => ({ meta: [{ title: "Dashboard | Mundo Vem Service Desk" }, { name: "description", content: "Indicadores do Service Desk conforme o perfil de acesso." }, { name: "robots", content: "noindex, follow" }] }),
  beforeLoad: async () => { const { data } = await supabase.auth.getUser(); if (!data.user) throw redirect({ to: "/auth" }); },
  component: DashboardPage,
});

const ENCERRADOS = ["resolvido", "fechado", "cancelado"];
const COR_PRIORIDADE: Record<string,string> = { critica:"#D13438", alta:"#F7A800", media:"#0078D4", baixa:"#107C10" };
const PERIODOS = [7,15,30,90] as const;
type Chamado = { id:string; numero:string; titulo:string; status:string; prioridade:string; criado_em:string; aberto_em:string; resolvido_em:string|null; sla_resolucao_violado:boolean; prazo_resolucao:string|null; sla_pausado:boolean; categoria_id:string|null; atendente_id:string|null; solicitante_id:string; segmento_id:string|null };
type Area = { id:string; nome:string };

function getArea(): Area|null { try { const raw=localStorage.getItem("service_desk_segmento"); if(!raw) return null; const v=JSON.parse(raw); return v?.id ? {id:String(v.id),nome:String(v.nome??"")} : null; } catch { return null; } }
function slaStatus(c:Chamado,now:number){ if(c.sla_pausado)return "pausado"; if(!c.prazo_resolucao)return "sem_sla"; const sec=(new Date(c.prazo_resolucao).getTime()-now)/1000; if(sec<=0)return "vencido"; if(sec<=3600)return "vencendo"; return "ok"; }
function statusLabel(s:string){ return ({aberto:"Aberto",em_andamento:"Em andamento",aguardando_usuario:"Aguardando usuário",aguardando_terceiro:"Aguardando terceiro",resolvido:"Resolvido",fechado:"Fechado",cancelado:"Cancelado"} as Record<string,string>)[s]??s; }
function statusStyle(s:string){ if(s==="aberto")return "bg-sky-100 text-sky-700"; if(s==="em_andamento")return "bg-amber-100 text-amber-700"; if(s==="resolvido")return "bg-emerald-100 text-emerald-700"; if(s==="fechado")return "bg-violet-100 text-violet-700"; return "bg-muted text-muted-foreground"; }
function prioridadeStyle(p:string){ if(p==="critica")return "bg-red-100 text-red-700 border-red-200"; if(p==="alta")return "bg-amber-100 text-amber-700 border-amber-200"; if(p==="media")return "bg-blue-100 text-blue-700 border-blue-200"; return "bg-emerald-100 text-emerald-700 border-emerald-200"; }

function DashboardPage(){
  const {user}=Route.useRouteContext(); const navigate=useNavigate(); const area=getArea();
  const [now,setNow]=useState(Date.now()); const [dias,setDias]=useState<number>(30); const [filtroStatus,setFiltroStatus]=useState("todos");
  useEffect(()=>{if(!area) navigate({to:"/areas",replace:true}); const t=window.setInterval(()=>setNow(Date.now()),30000); return()=>window.clearInterval(t);},[area,navigate]);
  const {data:roles=[],isLoading:loadingRoles}=useQuery({queryKey:["my-roles",user.id],queryFn:async()=>{const {data,error}=await supabase.from("user_roles").select("role").eq("user_id",user.id);if(error)throw error;return(data??[]).map(r=>String(r.role));}});
  const perfil=roles.includes("admin")?"admin":roles.includes("gestor")?"gestor":roles.includes("atendente")?"atendente":"colaborador";
  const isFull=perfil==="admin"||perfil==="gestor"; const since=useMemo(()=>{const d=new Date();d.setDate(d.getDate()-dias);return d.toISOString();},[dias]);
  const {data:chamados=[],isLoading}=useQuery({queryKey:["dashboard-chamados",perfil,user.id,dias,area?.id],enabled:!loadingRoles&&!!area,queryFn:async()=>{let q=(supabase as any).from("chamados").select("id,numero,titulo,status,prioridade,criado_em,aberto_em,resolvido_em,sla_resolucao_violado,prazo_resolucao,sla_pausado,categoria_id,atendente_id,solicitante_id,segmento_id").eq("segmento_id",area!.id).order("criado_em",{ascending:false}); if(isFull)q=q.gte("criado_em",since); if(perfil==="colaborador")q=q.eq("solicitante_id",user.id); if(perfil==="atendente")q=q.or(`atendente_id.eq.${user.id},atendente_id.is.null`); const {data,error}=await q;if(error)throw error;return(data??[]) as Chamado[];}});
  const {data:categorias=[]}=useQuery({queryKey:["dashboard-categorias",area?.id],enabled:!!area,queryFn:async()=>{const {data,error}=await supabase.from("categorias").select("id,nome").eq("ativo",true).eq("segmento_id",area!.id).order("ordem").order("nome");if(error)throw error;return data??[];}});
  const catMap=useMemo(()=>Object.fromEntries(categorias.map((c:any)=>[c.id,c.nome])),[categorias]);
  const active=(c:Chamado)=>!ENCERRADOS.includes(c.status); const resolved=(c:Chamado)=>c.status==="resolvido"||c.status==="fechado";
  const resumo=useMemo(()=>{const meus=chamados.filter(c=>c.atendente_id===user.id); const base=perfil==="atendente"?meus:chamados; const violados=base.filter(c=>c.sla_resolucao_violado||slaStatus(c,now)==="vencido").length; const resolvidos=base.filter(resolved).filter(c=>c.resolvido_em); const dur=resolvidos.map(c=>(new Date(c.resolvido_em!).getTime()-new Date(c.criado_em).getTime())/3600000); return {total:perfil==="atendente"?chamados.length:chamados.length,abertosAgora:(perfil==="atendente"?meus:chamados).filter(active).length,resolvidos:base.filter(resolved).length,taxaSla:base.length?Math.round(((base.length-violados)/base.length)*100):null,tMedio:dur.length?+(dur.reduce((a,b)=>a+b,0)/dur.length).toFixed(1):null,criticosAbertos:base.filter(c=>c.prioridade==="critica"&&active(c)).length,vencendo:base.filter(c=>slaStatus(c,now)==="vencendo").length,vencidos:base.filter(c=>slaStatus(c,now)==="vencido").length,pausados:base.filter(c=>slaStatus(c,now)==="pausado").length};},[chamados,now,perfil,user.id]);
  const porCategoria=useMemo(()=>{const base=perfil==="atendente"?chamados.filter(c=>c.atendente_id===user.id):chamados;const m=new Map<string,number>();base.forEach(c=>{const n=c.categoria_id?catMap[c.categoria_id]??"—":"—";m.set(n,(m.get(n)??0)+1);});return Array.from(m.entries()).map(([categoria,total])=>({categoria,total})).sort((a,b)=>b.total-a.total).slice(0,8);},[chamados,catMap,perfil,user.id]);
  const recentes=useMemo(()=>{let b=perfil==="atendente"?chamados.filter(c=>c.atendente_id===user.id):chamados;if(filtroStatus!=="todos")b=b.filter(c=>filtroStatus==="abertos"?c.status==="aberto":filtroStatus==="andamento"?c.status==="em_andamento":resolved(c));return b.slice(0,10);},[chamados,filtroStatus,perfil,user.id]);
  const volume=useMemo(()=>{if(!isFull)return[];const m=new Map<string,{dia:string;abertos:number;resolvidos:number}>();for(let i=dias-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=d.toISOString().slice(0,10);m.set(k,{dia:k.slice(5),abertos:0,resolvidos:0});}chamados.forEach(c=>{const a=m.get(c.criado_em.slice(0,10));if(a)a.abertos++;if(c.resolvido_em){const r=m.get(c.resolvido_em.slice(0,10));if(r)r.resolvidos++;}});return Array.from(m.values());},[chamados,dias,isFull]);
  const slaPorPrioridade=useMemo(()=>["baixa","media","alta","critica"].map(p=>{const i=chamados.filter(c=>c.prioridade===p);const v=i.filter(c=>c.sla_resolucao_violado||slaStatus(c,now)==="vencido").length;return{prioridade:p,taxa_pct:i.length?Math.round(((i.length-v)/i.length)*100):0};}),[chamados,now]);
  if(!area||loadingRoles||isLoading)return <div className="p-8 text-center text-sm text-muted-foreground">Carregando dashboard…</div>;
  if(perfil==="colaborador")return <SimpleDashboard titulo={`Meus chamados — ${area.nome}`} descricao="Acompanhe somente os chamados abertos por você nesta área." cards={[["Total chamados",resumo.total],["Abertos agora",resumo.abertosAgora],["Resolvidos",resumo.resolvidos]]} recentes={recentes} catMap={catMap} showFilters={false}/>;
  if(perfil==="atendente")return <AttendantDashboard area={area} resumo={resumo} recentes={recentes} porCategoria={porCategoria} catMap={catMap}/>;
  return <div className="space-y-4">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">Dashboard Gerencial — {area.nome}</h1><p className="text-sm text-muted-foreground">{perfil==="gestor"?"Métricas somente dos chamados da sua equipe nesta área.":"Métricas da área selecionada."}</p></div><div className="flex gap-2">{PERIODOS.map(d=><Button key={d} size="sm" variant={dias===d?"default":"outline"} onClick={()=>setDias(d)}>{d}d</Button>)}</div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Kpi label="Total chamados" valor={resumo.total}/><Kpi label="Abertos agora" valor={resumo.abertosAgora}/><Kpi label="Resolvidos" valor={resumo.resolvidos}/><Kpi label="Taxa SLA" valor={resumo.taxaSla!==null?`${resumo.taxaSla}%`:"—"} destaque={resumo.taxaSla!==null&&resumo.taxaSla>=80}/><Kpi label="T. médio resolução" valor={resumo.tMedio!==null?(resumo.tMedio<1?`${Math.round(resumo.tMedio*60)}min`:`${resumo.tMedio}h`):"—"}/><Kpi label="Críticos abertos" valor={resumo.criticosAbertos}/><Kpi label="SLA vencendo" valor={resumo.vencendo}/><Kpi label="SLA vencido" valor={resumo.vencidos}/><Kpi label="SLA pausado" valor={resumo.pausados}/></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Volume de chamados por dia</CardTitle></CardHeader><CardContent><ResponsiveContainer width="100%" height={220}><LineChart data={volume}><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis dataKey="dia" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}} allowDecimals={false}/><Tooltip/><Legend/><Line type="monotone" dataKey="abertos" stroke="#0078D4" strokeWidth={2} name="Abertos"/><Line type="monotone" dataKey="resolvidos" stroke="#107C10" strokeWidth={2} name="Resolvidos"/></LineChart></ResponsiveContainer></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">SLA por prioridade</CardTitle></CardHeader><CardContent><ResponsiveContainer width="100%" height={220}><BarChart data={slaPorPrioridade}><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis dataKey="prioridade" tick={{fontSize:10}}/><YAxis unit="%" domain={[0,100]} tick={{fontSize:10}}/><Tooltip/><Bar dataKey="taxa_pct" name="Taxa SLA" radius={[4,4,0,0]}>{slaPorPrioridade.map(i=><Cell key={i.prioridade} fill={COR_PRIORIDADE[i.prioridade]}/>)}</Bar></BarChart></ResponsiveContainer></CardContent></Card></div>
    <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Chamados por categoria</CardTitle></CardHeader><CardContent><ResponsiveContainer width="100%" height={240}><BarChart data={porCategoria} layout="vertical"><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="categoria" type="category" width={130}/><Tooltip/><Bar dataKey="total" fill="#0078D4" name="Total" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></CardContent></Card>
    <Recentes recentes={recentes} catMap={catMap} filtroStatus={filtroStatus} setFiltroStatus={setFiltroStatus}/>
  </div>;
}

function AttendantDashboard({area,resumo,recentes,porCategoria,catMap}:{area:Area;resumo:any;recentes:Chamado[];porCategoria:any[];catMap:Record<string,string>}){return <div className="space-y-4"><div><h1 className="text-2xl font-bold">Meu Dashboard — {area.nome}</h1><p className="text-sm text-muted-foreground">Indicadores da sua fila e dos seus chamados nesta área.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Total chamados" valor={resumo.total} sub="em seu nome ou sem atendente"/><Kpi label="Abertos agora" valor={resumo.abertosAgora}/><Kpi label="Taxa SLA" valor={resumo.taxaSla!==null?`${resumo.taxaSla}%`:"—"}/><Kpi label="T. médio resolução" valor={resumo.tMedio!==null?(resumo.tMedio<1?`${Math.round(resumo.tMedio*60)}min`:`${resumo.tMedio}h`):"—"}/><Kpi label="Críticos abertos" valor={resumo.criticosAbertos}/><Kpi label="SLA vencendo" valor={resumo.vencendo}/><Kpi label="SLA vencido" valor={resumo.vencidos}/><Kpi label="SLA pausado" valor={resumo.pausados}/></div><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Chamados por categoria</CardTitle></CardHeader><CardContent><ResponsiveContainer width="100%" height={260}><BarChart data={porCategoria} layout="vertical"><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="categoria" type="category" width={140}/><Tooltip/><Bar dataKey="total" fill="#0078D4" name="Total"/></BarChart></ResponsiveContainer></CardContent></Card><Recentes recentes={recentes} catMap={catMap} filtroStatus="todos" setFiltroStatus={()=>undefined} somenteEmMeuNome showFilters={false}/></div>}
function SimpleDashboard({titulo,descricao,cards,recentes,catMap,showFilters}:{titulo:string;descricao:string;cards:[string,number][];recentes:Chamado[];catMap:Record<string,string>;showFilters:boolean}){return <div className="space-y-4"><div><h1 className="text-2xl font-bold">{titulo}</h1><p className="text-sm text-muted-foreground">{descricao}</p></div><div className="grid gap-3 sm:grid-cols-3">{cards.map(([l,v])=><Kpi key={l} label={l} valor={v}/>)}</div><Recentes recentes={recentes} catMap={catMap} filtroStatus="todos" setFiltroStatus={()=>undefined} showFilters={showFilters}/></div>}
function Recentes({recentes,catMap,filtroStatus,setFiltroStatus,somenteEmMeuNome,showFilters=true}:{recentes:Chamado[];catMap:Record<string,string>;filtroStatus:string;setFiltroStatus:(s:string)=>void;somenteEmMeuNome?:boolean;showFilters?:boolean}){return <Card><CardHeader className="pb-2 flex flex-row items-center justify-between"><div><CardTitle className="text-sm">Chamados recentes</CardTitle>{somenteEmMeuNome&&<p className="text-xs text-muted-foreground mt-1">Somente chamados atribuídos a você.</p>}</div>{showFilters&&<div className="flex gap-1">{["todos","abertos","andamento","resolvidos"].map(s=><Button key={s} size="sm" variant={filtroStatus===s?"default":"outline"} onClick={()=>setFiltroStatus(s)} className="h-7 text-xs">{s==="andamento"?"Em andamento":s[0].toUpperCase()+s.slice(1)}</Button>)}</div>}</CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-xs text-muted-foreground border-b"><tr className="text-left"><th className="py-2 pr-3">#</th><th className="py-2 pr-3">Título</th><th className="py-2 pr-3">Categoria</th><th className="py-2 pr-3">Prioridade</th><th className="py-2 pr-3">Status</th><th className="py-2 pr-3">Aberto em</th></tr></thead><tbody>{recentes.length===0?<tr><td colSpan={6} className="py-6 text-center text-muted-foreground">Nenhum chamado encontrado.</td></tr>:recentes.map(c=><tr key={c.id} className="border-b last:border-0 hover:bg-muted/40"><td className="py-2 pr-3 font-medium text-muted-foreground">{c.numero}</td><td className="py-2 pr-3 font-medium"><Link to="/chamados/$id" params={{id:c.id}} className="hover:underline">{c.titulo}</Link></td><td className="py-2 pr-3"><Badge variant="secondary" className="font-normal">{c.categoria_id?catMap[c.categoria_id]??"—":"—"}</Badge></td><td className="py-2 pr-3"><span className={`inline-block rounded-full border px-2 py-0.5 text-xs font-medium ${prioridadeStyle(c.prioridade)}`}>{c.prioridade}</span></td><td className="py-2 pr-3"><span className={`inline-block rounded-full px-2 py-0.5 text-xs font-medium ${statusStyle(c.status)}`}>{statusLabel(c.status)}</span></td><td className="py-2 pr-3 text-muted-foreground">{new Date(c.aberto_em).toLocaleDateString("pt-BR")}</td></tr>)}</tbody></table></CardContent></Card>}
function Kpi({label,valor,sub,destaque}:{label:string;valor:string|number;sub?:string;destaque?:boolean}){return <Card className={destaque?"bg-primary text-primary-foreground border-primary":""}><CardContent className="p-4"><div className={`text-[10px] uppercase tracking-wider ${destaque?"text-primary-foreground/75":"text-muted-foreground"}`}>{label}</div><div className="mt-1 text-2xl font-semibold">{valor}</div>{sub&&<div className={`mt-1 text-[11px] ${destaque?"text-primary-foreground/70":"text-muted-foreground"}`}>{sub}</div>}</CardContent></Card>}
