import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Monitor, Plus, X, Eye, Pencil, Trash2 } from "lucide-react";

const STATUS: Record<string,string> = { ativo:"Ativo", inativo:"Inativo", manutencao:"Em manutenção", descartado:"Descartado" };
export const Route = createFileRoute("/_authenticated/itsm-ativos")({ component: ItsmAtivos });
function ItsmAtivos() {
 const qc=useQueryClient(); const [open,setOpen]=useState(false),[selected,setSelected]=useState<any>(null),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[formError,setFormError]=useState<string|null>(null);
 const [form,setForm]=useState({codigo_patrimonio:"",nome:"",tipo:"",status:"ativo",fabricante:"",modelo:"",numero_serie:"",ambiente:"",localizacao:"",responsavel_nome:"",valor:"",data_aquisicao:"",fim_garantia:"",dados_tecnicos:""});
 const {data,isLoading,error}=useQuery({queryKey:["itsm-ativos"],queryFn:async()=>{const {data,error}=await supabase.from("itsm_ativos").select("*").order("criado_em",{ascending:false});if(error)throw error;return data??[];}});
 const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v})); const reset=()=>setForm({codigo_patrimonio:"",nome:"",tipo:"",status:"ativo",fabricante:"",modelo:"",numero_serie:"",ambiente:"",localizacao:"",responsavel_nome:"",valor:"",data_aquisicao:"",fim_garantia:"",dados_tecnicos:""});
 const load=(x:any)=>setForm({codigo_patrimonio:x.codigo_patrimonio??"",nome:x.nome??"",tipo:x.tipo??"",status:x.status??"ativo",fabricante:x.fabricante??"",modelo:x.modelo??"",numero_serie:x.numero_serie??"",ambiente:x.ambiente??"",localizacao:x.localizacao??"",responsavel_nome:x.responsavel_nome??"",valor:x.valor==null?"":String(x.valor),data_aquisicao:x.data_aquisicao??"",fim_garantia:x.fim_garantia??"",dados_tecnicos:x.dados_tecnicos??""});
 const abrirDetalhes=(x:any)=>{setSelected(x);setEditing(false);setFormError(null);window.setTimeout(()=>document.getElementById("itsm-ativo-detalhes")?.scrollIntoView({behavior:"smooth",block:"start"}),50);};
 const save=async()=>{setFormError(null);if(!form.nome.trim())return setFormError("Informe o nome do ativo.");if(!form.tipo.trim())return setFormError("Informe o tipo do ativo.");setSaving(true);const p:any={codigo_patrimonio:form.codigo_patrimonio.trim()||null,nome:form.nome.trim(),tipo:form.tipo.trim(),status:form.status,fabricante:form.fabricante.trim()||null,modelo:form.modelo.trim()||null,numero_serie:form.numero_serie.trim()||null,ambiente:form.ambiente.trim()||null,localizacao:form.localizacao.trim()||null,responsavel_nome:form.responsavel_nome.trim()||null,valor:form.valor?Number(form.valor):null,data_aquisicao:form.data_aquisicao||null,fim_garantia:form.fim_garantia||null,dados_tecnicos:form.dados_tecnicos.trim()||null,atualizado_em:new Date().toISOString()};const r=editing?await supabase.from("itsm_ativos").update(p).eq("id",selected.id).select("*").single():await supabase.from("itsm_ativos").insert(p).select("*").single();setSaving(false);if(r.error)return setFormError(r.error.message);setSelected(r.data);setOpen(false);setEditing(false);reset();await qc.invalidateQueries({queryKey:["itsm-ativos"]});};
 const remove=async()=>{if(!selected||!window.confirm(`Excluir o ativo "${selected.nome}"?`))return;setSaving(true);const {error}=await supabase.from("itsm_ativos").delete().eq("id",selected.id);setSaving(false);if(error)return setFormError(error.message);setSelected(null);await qc.invalidateQueries({queryKey:["itsm-ativos"]});};
 return <div className="space-y-6"><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Ativos / CMDB</h1><p className="text-sm text-muted-foreground">Cadastro e controle do ciclo de vida dos ativos de TI.</p></div><Button onClick={()=>{reset();setSelected(null);setEditing(false);setOpen(true)}}><Plus className="mr-2 h-4 w-4"/>Novo ativo</Button></div>
 {(open||editing)&&<Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>{editing?"Editar ativo":"Novo ativo"}</CardTitle><Button variant="ghost" size="icon" onClick={()=>{setOpen(false);setEditing(false)}}><X className="h-4 w-4"/></Button></CardHeader><CardContent className="space-y-5"><div className="grid gap-4 md:grid-cols-2">{[["codigo_patrimonio","Código de patrimônio"],["nome","Nome *"],["tipo","Tipo *"],["fabricante","Fabricante"],["modelo","Modelo"],["numero_serie","Número de série"],["ambiente","Ambiente"],["localizacao","Localização"],["responsavel_nome","Responsável"],["valor","Valor"]].map(([k,l])=><div className="space-y-2" key={k}><Label>{l}</Label><Input type={k==="valor"?"number":"text"} value={(form as any)[k]} onChange={e=>set(k,e.target.value)} placeholder={k==="responsavel_nome"?"Nome da pessoa responsável":""}/></div>)}<div className="space-y-2"><Label>Status</Label><Select value={form.status} onValueChange={v=>set("status",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(STATUS).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Data de aquisição</Label><Input type="date" value={form.data_aquisicao} onChange={e=>set("data_aquisicao",e.target.value)}/></div><div className="space-y-2"><Label>Fim da garantia</Label><Input type="date" value={form.fim_garantia} onChange={e=>set("fim_garantia",e.target.value)}/></div><div className="space-y-2 md:col-span-2"><Label>Dados técnicos</Label><Textarea value={form.dados_tecnicos} onChange={e=>set("dados_tecnicos",e.target.value)} placeholder="Ex.: iPhone 15, número xxxx-xxxx, usuário, 128 GB, IMEI..." /></div></div>{formError&&<p className="text-sm text-destructive">{formError}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>{setOpen(false);setEditing(false)}}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?"Salvando...":editing?"Salvar alterações":"Criar ativo"}</Button></div></CardContent></Card>}
 {selected&&!editing&&<Card id="itsm-ativo-detalhes" className="scroll-mt-6 border-primary/50 shadow-sm ring-1 ring-primary/20"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="flex items-center gap-2"><Eye className="h-5 w-5"/>{selected.nome}</CardTitle><p className="text-sm text-muted-foreground">Detalhes do ativo · {selected.codigo_patrimonio??`Ativo #${selected.id}`}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>{load(selected);setEditing(true)}}><Pencil className="mr-2 h-4 w-4"/>Editar</Button><Button variant="destructive" size="sm" onClick={remove} disabled={saving}><Trash2 className="mr-2 h-4 w-4"/>Excluir</Button><Button variant="ghost" size="icon" onClick={()=>setSelected(null)}><X className="h-4 w-4"/></Button></div></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["Status",STATUS[selected.status]??selected.status],["Tipo",selected.tipo],["Fabricante",selected.fabricante],["Modelo",selected.modelo],["Nº série",selected.numero_serie],["Ambiente",selected.ambiente],["Localização",selected.localizacao],["Responsável",selected.responsavel_nome],["Valor",selected.valor],["Aquisição",selected.data_aquisicao],["Garantia",selected.fim_garantia]].map(([l,v])=><Detail key={l} label={l} value={v}/>)}</div><Detail label="Dados técnicos" value={selected.dados_tecnicos} multi/></CardContent></Card>}
 {error&&<Card><CardContent className="pt-6 text-sm text-destructive">Não foi possível carregar os ativos.</CardContent></Card>}<Card><CardHeader><CardTitle className="flex items-center gap-2"><Monitor className="h-5 w-5"/> Ativos registrados</CardTitle></CardHeader><CardContent>{isLoading?<p className="text-sm text-muted-foreground">Carregando...</p>:data?.length?<div className="space-y-3">{data.map((x:any)=><div key={x.id} className="flex items-center justify-between gap-4 rounded-lg border p-4"><div><div className="font-medium">{x.nome}</div><div className="text-sm text-muted-foreground">{x.codigo_patrimonio??"Sem patrimônio"} · {x.tipo} · {STATUS[x.status]??x.status}</div></div><Button variant="outline" size="sm" onClick={()=>abrirDetalhes(x)}><Eye className="mr-2 h-4 w-4"/>Ver detalhes</Button></div>)}</div>:<p className="text-sm text-muted-foreground">Nenhum ativo registrado.</p>}</CardContent></Card></div>;
}
function Detail({label,value,multi=false}:{label:string,value:any,multi?:boolean}){return <div className={multi?"space-y-1 md:col-span-2":"space-y-1"}><div className="text-xs font-medium text-muted-foreground">{label}</div><div className={multi?"whitespace-pre-wrap rounded-md border p-3 text-sm":"text-sm"}>{value==null||value===""?"-":String(value)}</div></div>}
