import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ClipboardCheck, Plus, Pencil, Eye, X, AlertTriangle } from "lucide-react";
export const Route=createFileRoute("/_authenticated/itsm-governanca")({component:ItsmGovernanca});
type Policy={id:string;nome:string;descricao:string|null;tipo:string;status:string;responsavel_id:string|null;aprovador_id:string|null;vigencia_inicio:string|null;vigencia_fim:string|null;periodicidade_revisao:string|null;evidencias:unknown;criado_em:string;atualizado_em:string};
type Summary={total_chamados:number;chamados_abertos:number;problemas_abertos:number;mudancas_pendentes:number;ativos_ativos:number;servicos_ativos:number;relacionamentos:number;artigos_publicados:number;eventos_auditoria:number;politicas_vigentes:number};
const statusLabel:Record<string,string>={rascunho:"Rascunho",em_revisao:"Em revisão",aprovado:"Aprovado",vigente:"Vigente",encerrado:"Encerrado"};
function ItsmGovernanca(){
 const qc=useQueryClient();const[open,setOpen]=useState(false),[editing,setEditing]=useState<Policy|null>(null),[selected,setSelected]=useState<Policy|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);const[nome,setNome]=useState(""),[descricao,setDescricao]=useState(""),[tipo,setTipo]=useState("politica"),[status,setStatus]=useState("rascunho"),[periodicidade,setPeriodicidade]=useState(""),[inicio,setInicio]=useState(""),[fim,setFim]=useState("");
 const{data,isLoading}=useQuery({queryKey:["itsm-governanca"],queryFn:async()=>{const{data,error}=await supabase.from("itsm_politicas_governanca").select("*").order("nome");if(error)throw error;return(data??[])as Policy[]}});const{data:summary}=useQuery({queryKey:["itsm-governanca-resumo"],queryFn:async()=>{const{data,error}=await supabase.from("itsm_governanca_resumo").select("*").single();if(error)throw error;return data as Summary}});
 const policyUserIds=Array.from(new Set((data??[]).flatMap(p=>[p.responsavel_id,p.aprovador_id].filter(Boolean)))) as string[];const{data:profiles=[]}=useQuery({queryKey:["itsm-governanca-profiles",policyUserIds.join(",")],enabled:policyUserIds.length>0,queryFn:async()=>{const{data,error}=await supabase.from("profiles").select("id,nome,email").in("id",policyUserIds);return error?[]:data??[]}});const profileMap=Object.fromEntries((profiles as any[]).map(p=>[p.id,p.nome||p.email||p.id]));
 const reset=()=>{setNome("");setDescricao("");setTipo("politica");setStatus("rascunho");setPeriodicidade("");setInicio("");setFim("");setError(null)};const edit=(p?:Policy)=>{if(p){setEditing(p);setNome(p.nome);setDescricao(p.descricao??"");setTipo(p.tipo);setStatus(p.status);setPeriodicidade(p.periodicidade_revisao??"");setInicio(p.vigencia_inicio??"");setFim(p.vigencia_fim??"")}else{setEditing(null);reset()}setOpen(true)};
 const save=async()=>{if(!nome.trim())return setError("Informe o nome.");if(inicio&&fim&&fim<inicio)return setError("O fim da vigência deve ser posterior ao início.");setSaving(true);setError(null);const user=(await supabase.auth.getUser()).data.user;const payload={nome:nome.trim(),descricao:descricao.trim()||null,tipo,status,periodicidade_revisao:periodicidade.trim()||null,vigencia_inicio:inicio||null,vigencia_fim:fim||null,atualizado_em:new Date().toISOString()};const result=editing?await supabase.from("itsm_politicas_governanca").update(payload).eq("id",editing.id).select("*").single():await supabase.from("itsm_politicas_governanca").insert({...payload,responsavel_id:user?.id??null}).select("*").single();setSaving(false);if(result.error)return setError(result.error.message);setSelected(result.data as Policy);setOpen(false);setEditing(null);reset();await Promise.all([qc.invalidateQueries({queryKey:["itsm-governanca"]}),qc.invalidateQueries({queryKey:["itsm-governanca-resumo"]})])};
 return <div className="space-y-6"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><ClipboardCheck className="h-6 w-6 text-primary"/><h1 className="text-2xl font-semibold tracking-tight">Governança</h1></div><p className="text-sm text-muted-foreground">Controle de políticas, riscos operacionais, indicadores e evidências do ITSM.</p></div><Button onClick={()=>edit()}><Plus className="mr-2 h-4 w-4"/>Nova política</Button></div>
 {summary&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Chamados abertos",summary.chamados_abertos],["Problemas abertos",summary.problemas_abertos],["Mudanças pendentes",summary.mudancas_pendentes],["Ativos ativos",summary.ativos_ativos],["Serviços ativos",summary.servicos_ativos],["Relacionamentos",summary.relacionamentos],["Artigos publicados",summary.artigos_publicados],["Eventos de auditoria",summary.eventos_auditoria],["Políticas vigentes",summary.politicas_vigentes],["Total de chamados",summary.total_chamados]].map(([l,v])=><Card key={String(l)}><CardContent className="pt-5"><div className="text-xs text-muted-foreground">{l}</div><div className="mt-1 text-2xl font-semibold">{v}</div></CardContent></Card>)}</div>}
 {summary&&summary.chamados_abertos>0&&summary.problemas_abertos>0&&<Card className="border-amber-500/40"><CardContent className="flex items-center gap-3 pt-5 text-sm"><AlertTriangle className="h-5 w-5"/><span>Existem chamados e problemas em aberto. Acompanhe capacidade, recorrência e risco operacional.</span></CardContent></Card>}
 {open&&<Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>{editing?"Editar política":"Nova política"}</CardTitle><Button variant="ghost" size="icon" onClick={()=>{setOpen(false);setEditing(null);reset()}}><X className="h-4 w-4"/></Button></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Nome *</Label><Input value={nome} onChange={e=>setNome(e.target.value)}/></div><div className="space-y-2"><Label>Tipo</Label><Select value={tipo} onValueChange={setTipo}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="politica">Política</SelectItem><SelectItem value="processo">Processo</SelectItem><SelectItem value="controle">Controle</SelectItem><SelectItem value="padrao">Padrão</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Status</Label><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(statusLabel).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Periodicidade de revisão</Label><Input value={periodicidade} onChange={e=>setPeriodicidade(e.target.value)} placeholder="Ex.: anual"/></div><div className="space-y-2"><Label>Início da vigência</Label><Input type="date" value={inicio} onChange={e=>setInicio(e.target.value)}/></div><div className="space-y-2"><Label>Fim da vigência</Label><Input type="date" value={fim} onChange={e=>setFim(e.target.value)}/></div><div className="space-y-2 md:col-span-2"><Label>Descrição</Label><Textarea rows={6} value={descricao} onChange={e=>setDescricao(e.target.value)}/></div></div>{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>{setOpen(false);setEditing(null);reset()}}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?"Salvando...":"Salvar"}</Button></div></CardContent></Card>}
 {selected&&!open&&<Card className="border-primary/50"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>{selected.nome}</CardTitle><p className="text-sm text-muted-foreground">{selected.tipo} · {statusLabel[selected.status]??selected.status}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>edit(selected)}><Pencil className="mr-2 h-4 w-4"/>Editar</Button><Button variant="ghost" size="icon" onClick={()=>setSelected(null)}><X className="h-4 w-4"/></Button></div></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm">{selected.descricao??"Sem descrição."}</p><div className="mt-4 grid gap-4 md:grid-cols-3"><Detail l="Vigência" v={selected.vigencia_inicio?`${selected.vigencia_inicio} → ${selected.vigencia_fim??"sem fim"}`:"Não definida"}/><Detail l="Revisão" v={selected.periodicidade_revisao}/><Detail l="Responsável" v={selected.responsavel_id?profileMap[selected.responsavel_id]??"Usuário":null}/></div></CardContent></Card>}
 <Card><CardHeader><CardTitle>Políticas e controles</CardTitle></CardHeader><CardContent>{isLoading?<p className="text-sm text-muted-foreground">Carregando...</p>:data?.length?<div className="space-y-3">{data.map(p=><div key={p.id} className="flex items-center justify-between gap-4 rounded-lg border p-4"><div><div className="font-medium">{p.nome}</div><div className="text-sm text-muted-foreground">{p.tipo} · {statusLabel[p.status]??p.status}{p.periodicidade_revisao?` · revisão ${p.periodicidade_revisao}`:""}</div></div><Button variant="outline" size="sm" onClick={()=>setSelected(p)}><Eye className="mr-2 h-4 w-4"/>Ver</Button></div>)}</div>:<p className="text-sm text-muted-foreground">Nenhuma política cadastrada.</p>}</CardContent></Card></div>}
function Detail({l,v}:{l:string;v:unknown}){return <div><div className="text-xs font-medium text-muted-foreground">{l}</div><div className="text-sm">{v==null||v===""?"-":String(v)}</div></div>}