/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssistenteRouteImport } from './routes/api/assistente'
import { Route as AuthenticatedFilaRouteImport } from './routes/_authenticated/fila'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedChamadosIndexRouteImport } from './routes/_authenticated/chamados.index'
import { Route as AuthenticatedBaseConhecimentoIndexRouteImport } from './routes/_authenticated/base-conhecimento.index'
import { Route as AuthenticatedAssistenteIndexRouteImport } from './routes/_authenticated/assistente.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiAssistenteBackupRouteImport } from './routes/api/assistente.backup'
import { Route as AuthenticatedChamadosNovoRouteImport } from './routes/_authenticated/chamados.novo'
import { Route as AuthenticatedChamadosIdRouteImport } from './routes/_authenticated/chamados.$id'
import { Route as AuthenticatedBaseConhecimentoNovoRouteImport } from './routes/_authenticated/base-conhecimento.novo'
import { Route as AuthenticatedBaseConhecimentoIdRouteImport } from './routes/_authenticated/base-conhecimento.$id'
import { Route as AuthenticatedAssistenteConversaIdRouteImport } from './routes/_authenticated/assistente.$conversaId'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminAssistenteRouteImport } from './routes/_authenticated/admin.assistente'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedBaseConhecimentoIdEditarRouteImport } from './routes/_authenticated/base-conhecimento.$id.editar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistenteRoute = ApiAssistenteRouteImport.update({
  id: '/api/assistente',
  path: '/api/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFilaRoute = AuthenticatedFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChamadosIndexRoute =
  AuthenticatedChamadosIndexRouteImport.update({
    id: '/chamados/',
    path: '/chamados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaseConhecimentoIndexRoute =
  AuthenticatedBaseConhecimentoIndexRouteImport.update({
    id: '/base-conhecimento/',
    path: '/base-conhecimento/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistenteIndexRoute =
  AuthenticatedAssistenteIndexRouteImport.update({
    id: '/assistente/',
    path: '/assistente/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAssistenteBackupRoute = ApiAssistenteBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => ApiAssistenteRoute,
} as any)
const AuthenticatedChamadosNovoRoute =
  AuthenticatedChamadosNovoRouteImport.update({
    id: '/chamados/novo',
    path: '/chamados/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChamadosIdRoute = AuthenticatedChamadosIdRouteImport.update({
  id: '/chamados/$id',
  path: '/chamados/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaseConhecimentoNovoRoute =
  AuthenticatedBaseConhecimentoNovoRouteImport.update({
    id: '/base-conhecimento/novo',
    path: '/base-conhecimento/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaseConhecimentoIdRoute =
  AuthenticatedBaseConhecimentoIdRouteImport.update({
    id: '/base-conhecimento/$id',
    path: '/base-conhecimento/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistenteConversaIdRoute =
  AuthenticatedAssistenteConversaIdRouteImport.update({
    id: '/assistente/$conversaId',
    path: '/assistente/$conversaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/admin/categorias',
    path: '/admin/categorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAssistenteRoute =
  AuthenticatedAdminAssistenteRouteImport.update({
    id: '/admin/assistente',
    path: '/admin/assistente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBaseConhecimentoIdEditarRoute =
  AuthenticatedBaseConhecimentoIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedBaseConhecimentoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/api/assistente': typeof ApiAssistenteRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/assistente': typeof AuthenticatedAdminAssistenteRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/assistente/$conversaId': typeof AuthenticatedAssistenteConversaIdRoute
  '/base-conhecimento/$id': typeof AuthenticatedBaseConhecimentoIdRouteWithChildren
  '/base-conhecimento/novo': typeof AuthenticatedBaseConhecimentoNovoRoute
  '/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/chamados/novo': typeof AuthenticatedChamadosNovoRoute
  '/api/assistente/backup': typeof ApiAssistenteBackupRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/assistente/': typeof AuthenticatedAssistenteIndexRoute
  '/base-conhecimento/': typeof AuthenticatedBaseConhecimentoIndexRoute
  '/chamados/': typeof AuthenticatedChamadosIndexRoute
  '/base-conhecimento/$id/editar': typeof AuthenticatedBaseConhecimentoIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/api/assistente': typeof ApiAssistenteRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/assistente': typeof AuthenticatedAdminAssistenteRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/assistente/$conversaId': typeof AuthenticatedAssistenteConversaIdRoute
  '/base-conhecimento/$id': typeof AuthenticatedBaseConhecimentoIdRouteWithChildren
  '/base-conhecimento/novo': typeof AuthenticatedBaseConhecimentoNovoRoute
  '/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/chamados/novo': typeof AuthenticatedChamadosNovoRoute
  '/api/assistente/backup': typeof ApiAssistenteBackupRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/assistente': typeof AuthenticatedAssistenteIndexRoute
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoIndexRoute
  '/chamados': typeof AuthenticatedChamadosIndexRoute
  '/base-conhecimento/$id/editar': typeof AuthenticatedBaseConhecimentoIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fila': typeof AuthenticatedFilaRoute
  '/api/assistente': typeof ApiAssistenteRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/assistente': typeof AuthenticatedAdminAssistenteRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/assistente/$conversaId': typeof AuthenticatedAssistenteConversaIdRoute
  '/_authenticated/base-conhecimento/$id': typeof AuthenticatedBaseConhecimentoIdRouteWithChildren
  '/_authenticated/base-conhecimento/novo': typeof AuthenticatedBaseConhecimentoNovoRoute
  '/_authenticated/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/_authenticated/chamados/novo': typeof AuthenticatedChamadosNovoRoute
  '/api/assistente/backup': typeof ApiAssistenteBackupRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/assistente/': typeof AuthenticatedAssistenteIndexRoute
  '/_authenticated/base-conhecimento/': typeof AuthenticatedBaseConhecimentoIndexRoute
  '/_authenticated/chamados/': typeof AuthenticatedChamadosIndexRoute
  '/_authenticated/base-conhecimento/$id/editar': typeof AuthenticatedBaseConhecimentoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/fila'
    | '/api/assistente'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/assistente'
    | '/admin/categorias'
    | '/admin/usuarios'
    | '/assistente/$conversaId'
    | '/base-conhecimento/$id'
    | '/base-conhecimento/novo'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/api/assistente/backup'
    | '/admin/'
    | '/assistente/'
    | '/base-conhecimento/'
    | '/chamados/'
    | '/base-conhecimento/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/fila'
    | '/api/assistente'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/assistente'
    | '/admin/categorias'
    | '/admin/usuarios'
    | '/assistente/$conversaId'
    | '/base-conhecimento/$id'
    | '/base-conhecimento/novo'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/api/assistente/backup'
    | '/admin'
    | '/assistente'
    | '/base-conhecimento'
    | '/chamados'
    | '/base-conhecimento/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/_authenticated/fila'
    | '/api/assistente'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/assistente'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/assistente/$conversaId'
    | '/_authenticated/base-conhecimento/$id'
    | '/_authenticated/base-conhecimento/novo'
    | '/_authenticated/chamados/$id'
    | '/_authenticated/chamados/novo'
    | '/api/assistente/backup'
    | '/_authenticated/admin/'
    | '/_authenticated/assistente/'
    | '/_authenticated/base-conhecimento/'
    | '/_authenticated/chamados/'
    | '/_authenticated/base-conhecimento/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAssistenteRoute: typeof ApiAssistenteRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistente': {
      id: '/api/assistente'
      path: '/api/assistente'
      fullPath: '/api/assistente'
      preLoaderRoute: typeof ApiAssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fila': {
      id: '/_authenticated/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof AuthenticatedFilaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chamados/': {
      id: '/_authenticated/chamados/'
      path: '/chamados'
      fullPath: '/chamados/'
      preLoaderRoute: typeof AuthenticatedChamadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento/': {
      id: '/_authenticated/base-conhecimento/'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento/'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente/': {
      id: '/_authenticated/assistente/'
      path: '/assistente'
      fullPath: '/assistente/'
      preLoaderRoute: typeof AuthenticatedAssistenteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/assistente/backup': {
      id: '/api/assistente/backup'
      path: '/backup'
      fullPath: '/api/assistente/backup'
      preLoaderRoute: typeof ApiAssistenteBackupRouteImport
      parentRoute: typeof ApiAssistenteRoute
    }
    '/_authenticated/chamados/novo': {
      id: '/_authenticated/chamados/novo'
      path: '/chamados/novo'
      fullPath: '/chamados/novo'
      preLoaderRoute: typeof AuthenticatedChamadosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamados/$id': {
      id: '/_authenticated/chamados/$id'
      path: '/chamados/$id'
      fullPath: '/chamados/$id'
      preLoaderRoute: typeof AuthenticatedChamadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento/novo': {
      id: '/_authenticated/base-conhecimento/novo'
      path: '/base-conhecimento/novo'
      fullPath: '/base-conhecimento/novo'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento/$id': {
      id: '/_authenticated/base-conhecimento/$id'
      path: '/base-conhecimento/$id'
      fullPath: '/base-conhecimento/$id'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente/$conversaId': {
      id: '/_authenticated/assistente/$conversaId'
      path: '/assistente/$conversaId'
      fullPath: '/assistente/$conversaId'
      preLoaderRoute: typeof AuthenticatedAssistenteConversaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/assistente': {
      id: '/_authenticated/admin/assistente'
      path: '/admin/assistente'
      fullPath: '/admin/assistente'
      preLoaderRoute: typeof AuthenticatedAdminAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/base-conhecimento/$id/editar': {
      id: '/_authenticated/base-conhecimento/$id/editar'
      path: '/editar'
      fullPath: '/base-conhecimento/$id/editar'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoIdEditarRouteImport
      parentRoute: typeof AuthenticatedBaseConhecimentoIdRoute
    }
  }
}

interface AuthenticatedBaseConhecimentoIdRouteChildren {
  AuthenticatedBaseConhecimentoIdEditarRoute: typeof AuthenticatedBaseConhecimentoIdEditarRoute
}

const AuthenticatedBaseConhecimentoIdRouteChildren: AuthenticatedBaseConhecimentoIdRouteChildren =
  {
    AuthenticatedBaseConhecimentoIdEditarRoute:
      AuthenticatedBaseConhecimentoIdEditarRoute,
  }

const AuthenticatedBaseConhecimentoIdRouteWithChildren =
  AuthenticatedBaseConhecimentoIdRoute._addFileChildren(
    AuthenticatedBaseConhecimentoIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilaRoute: typeof AuthenticatedFilaRoute
  AuthenticatedAdminAssistenteRoute: typeof AuthenticatedAdminAssistenteRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAssistenteConversaIdRoute: typeof AuthenticatedAssistenteConversaIdRoute
  AuthenticatedBaseConhecimentoIdRoute: typeof AuthenticatedBaseConhecimentoIdRouteWithChildren
  AuthenticatedBaseConhecimentoNovoRoute: typeof AuthenticatedBaseConhecimentoNovoRoute
  AuthenticatedChamadosIdRoute: typeof AuthenticatedChamadosIdRoute
  AuthenticatedChamadosNovoRoute: typeof AuthenticatedChamadosNovoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAssistenteIndexRoute: typeof AuthenticatedAssistenteIndexRoute
  AuthenticatedBaseConhecimentoIndexRoute: typeof AuthenticatedBaseConhecimentoIndexRoute
  AuthenticatedChamadosIndexRoute: typeof AuthenticatedChamadosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilaRoute: AuthenticatedFilaRoute,
  AuthenticatedAdminAssistenteRoute: AuthenticatedAdminAssistenteRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAssistenteConversaIdRoute:
    AuthenticatedAssistenteConversaIdRoute,
  AuthenticatedBaseConhecimentoIdRoute:
    AuthenticatedBaseConhecimentoIdRouteWithChildren,
  AuthenticatedBaseConhecimentoNovoRoute:
    AuthenticatedBaseConhecimentoNovoRoute,
  AuthenticatedChamadosIdRoute: AuthenticatedChamadosIdRoute,
  AuthenticatedChamadosNovoRoute: AuthenticatedChamadosNovoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAssistenteIndexRoute: AuthenticatedAssistenteIndexRoute,
  AuthenticatedBaseConhecimentoIndexRoute:
    AuthenticatedBaseConhecimentoIndexRoute,
  AuthenticatedChamadosIndexRoute: AuthenticatedChamadosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiAssistenteRouteChildren {
  ApiAssistenteBackupRoute: typeof ApiAssistenteBackupRoute
}

const ApiAssistenteRouteChildren: ApiAssistenteRouteChildren = {
  ApiAssistenteBackupRoute: ApiAssistenteBackupRoute,
}

const ApiAssistenteRouteWithChildren = ApiAssistenteRoute._addFileChildren(
  ApiAssistenteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAssistenteRoute: ApiAssistenteRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
