-- Fase 6 - ITSM Avançado
create table if not exists public.itsm_problemas (
  id uuid primary key default gen_random_uuid(), numero bigint generated by default as identity unique,
  titulo text not null, descricao text, status text not null default 'aberto', prioridade text not null default 'media',
  impacto text not null default 'medio', urgencia text not null default 'media', causa_raiz text, workaround text,
  responsavel_id uuid references public.profiles(id), data_identificacao timestamptz not null default now(), data_resolucao timestamptz,
  criado_por uuid references public.profiles(id), criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create table if not exists public.itsm_mudancas (
  id uuid primary key default gen_random_uuid(), numero bigint generated by default as identity unique, titulo text not null,
  descricao text, tipo text not null default 'normal', status text not null default 'rascunho', risco text not null default 'medio',
  impacto text not null default 'medio', justificativa text, plano_execucao text, plano_rollback text, janela_inicio timestamptz,
  janela_fim timestamptz, solicitante_id uuid references public.profiles(id), responsavel_id uuid references public.profiles(id),
  aprovador_id uuid references public.profiles(id), aprovado_em timestamptz, executado_em timestamptz,
  criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create table if not exists public.itsm_ativos (
  id uuid primary key default gen_random_uuid(), codigo_patrimonio text unique, nome text not null, tipo text not null,
  status text not null default 'ativo', fabricante text, modelo text, numero_serie text, ambiente text, localizacao text,
  responsavel_id uuid references public.profiles(id), valor numeric(14,2), data_aquisicao date, fim_garantia date,
  dados_tecnicos jsonb not null default '{}'::jsonb, criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create table if not exists public.itsm_relacionamentos (
  id uuid primary key default gen_random_uuid(), origem_tipo text not null, origem_id uuid not null, relacao text not null,
  destino_tipo text not null, destino_id uuid not null, criado_por uuid references public.profiles(id), criado_em timestamptz not null default now(),
  unique(origem_tipo, origem_id, relacao, destino_tipo, destino_id)
);
create table if not exists public.itsm_artigos_conhecimento (
  id uuid primary key default gen_random_uuid(), titulo text not null, resumo text, conteudo text not null, categoria text,
  status text not null default 'rascunho', versao integer not null default 1, autor_id uuid references public.profiles(id),
  revisor_id uuid references public.profiles(id), publicado_em timestamptz, revisao_em timestamptz, validade_em timestamptz,
  visualizacoes integer not null default 0, util integer not null default 0, nao_util integer not null default 0,
  criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create table if not exists public.itsm_auditoria (
  id uuid primary key default gen_random_uuid(), entidade text not null, entidade_id uuid, acao text not null,
  usuario_id uuid references public.profiles(id), antes jsonb, depois jsonb, criado_em timestamptz not null default now()
);
create table if not exists public.itsm_politicas_governanca (
  id uuid primary key default gen_random_uuid(), nome text not null, descricao text, tipo text not null default 'politica',
  status text not null default 'rascunho', responsavel_id uuid references public.profiles(id), aprovador_id uuid references public.profiles(id),
  vigencia_inicio date, vigencia_fim date, periodicidade_revisao text, evidencias jsonb not null default '[]'::jsonb,
  criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create index if not exists idx_itsm_problemas_status on public.itsm_problemas(status);
create index if not exists idx_itsm_mudancas_status on public.itsm_mudancas(status);
create index if not exists idx_itsm_ativos_status on public.itsm_ativos(status);
create index if not exists idx_itsm_rel_origem on public.itsm_relacionamentos(origem_tipo, origem_id);
create index if not exists idx_itsm_rel_destino on public.itsm_relacionamentos(destino_tipo, destino_id);
create index if not exists idx_itsm_artigos_status on public.itsm_artigos_conhecimento(status);
create index if not exists idx_itsm_auditoria_entidade on public.itsm_auditoria(entidade, entidade_id, criado_em desc);

create or replace function public.itsm_e_gestor_ou_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.user_roles ur where ur.user_id=auth.uid() and ur.role in ('gestor','admin'));
$$;
revoke all on function public.itsm_e_gestor_ou_admin() from public;
grant execute on function public.itsm_e_gestor_ou_admin() to authenticated;

alter table public.itsm_problemas enable row level security;
alter table public.itsm_mudancas enable row level security;
alter table public.itsm_ativos enable row level security;
alter table public.itsm_relacionamentos enable row level security;
alter table public.itsm_artigos_conhecimento enable row level security;
alter table public.itsm_auditoria enable row level security;
alter table public.itsm_politicas_governanca enable row level security;

do $$ begin create policy "ITSM gestores administram problemas" on public.itsm_problemas for all to authenticated using(public.itsm_e_gestor_ou_admin()) with check(public.itsm_e_gestor_ou_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy "ITSM gestores administram mudancas" on public.itsm_mudancas for all to authenticated using(public.itsm_e_gestor_ou_admin()) with check(public.itsm_e_gestor_ou_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy "ITSM gestores administram ativos" on public.itsm_ativos for all to authenticated using(public.itsm_e_gestor_ou_admin()) with check(public.itsm_e_gestor_ou_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy "ITSM gestores administram relacionamentos" on public.itsm_relacionamentos for all to authenticated using(public.itsm_e_gestor_ou_admin()) with check(public.itsm_e_gestor_ou_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy "ITSM gestores administram conhecimento" on public.itsm_artigos_conhecimento for all to authenticated using(public.itsm_e_gestor_ou_admin()) with check(public.itsm_e_gestor_ou_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy "ITSM gestores consultam auditoria" on public.itsm_auditoria for select to authenticated using(public.itsm_e_gestor_ou_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy "ITSM gestores administram governanca" on public.itsm_politicas_governanca for all to authenticated using(public.itsm_e_gestor_ou_admin()) with check(public.itsm_e_gestor_ou_admin()); exception when duplicate_object then null; end $$;

grant select,insert,update,delete on public.itsm_problemas to authenticated;
grant select,insert,update,delete on public.itsm_mudancas to authenticated;
grant select,insert,update,delete on public.itsm_ativos to authenticated;
grant select,insert,update,delete on public.itsm_relacionamentos to authenticated;
grant select,insert,update,delete on public.itsm_artigos_conhecimento to authenticated;
grant select on public.itsm_auditoria to authenticated;
grant select,insert,update,delete on public.itsm_politicas_governanca to authenticated;

create or replace function public.itsm_registrar_auditoria() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.itsm_auditoria(entidade,entidade_id,acao,usuario_id,antes,depois)
  values(tg_table_name,coalesce(new.id,old.id),tg_op,auth.uid(),to_jsonb(old),to_jsonb(new));
  return coalesce(new,old);
end; $$;

DROP TRIGGER IF EXISTS trg_itsm_audit_problemas ON public.itsm_problemas;
CREATE TRIGGER trg_itsm_audit_problemas AFTER INSERT OR UPDATE OR DELETE ON public.itsm_problemas FOR EACH ROW EXECUTE FUNCTION public.itsm_registrar_auditoria();
DROP TRIGGER IF EXISTS trg_itsm_audit_mudancas ON public.itsm_mudancas;
CREATE TRIGGER trg_itsm_audit_mudancas AFTER INSERT OR UPDATE OR DELETE ON public.itsm_mudancas FOR EACH ROW EXECUTE FUNCTION public.itsm_registrar_auditoria();
DROP TRIGGER IF EXISTS trg_itsm_audit_ativos ON public.itsm_ativos;
CREATE TRIGGER trg_itsm_audit_ativos AFTER INSERT OR UPDATE OR DELETE ON public.itsm_ativos FOR EACH ROW EXECUTE FUNCTION public.itsm_registrar_auditoria();
DROP TRIGGER IF EXISTS trg_itsm_audit_artigos ON public.itsm_artigos_conhecimento;
CREATE TRIGGER trg_itsm_audit_artigos AFTER INSERT OR UPDATE OR DELETE ON public.itsm_artigos_conhecimento FOR EACH ROW EXECUTE FUNCTION public.itsm_registrar_auditoria();
DROP TRIGGER IF EXISTS trg_itsm_audit_governanca ON public.itsm_politicas_governanca;
CREATE TRIGGER trg_itsm_audit_governanca AFTER INSERT OR UPDATE OR DELETE ON public.itsm_politicas_governanca FOR EACH ROW EXECUTE FUNCTION public.itsm_registrar_auditoria();
